version: '3'

services:
  app:
    build: .
    env_file: .env
    environment: 
      - PORT=3000
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=admin
      - MYSQL_ROOT_HOST=%
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app

  mysql:
    image: mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=admin
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
            
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
                  